services:
  interview_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    environment:
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
