export const USERS = [
  {
    id: 1,
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    gender: 'Male',
    ip_address: '192.168.1.1',
    days: 120,
    created_at: new Date('2023-05-01'),
  },
  {
    id: 2,
    first_name: 'Jane',
    last_name: 'Doe',
    email: 'jane.doe@example.com',
    gender: 'Female',
    ip_address: '192.168.1.2',
    days: 90,
    created_at: new Date('2023-06-01'),
  },
  {
    id: 3,
    first_name: 'Bob',
    last_name: 'Smith',
    email: 'bob.smith@example.com',
    gender: 'Male',
    ip_address: '192.168.1.3',
    days: 180,
    created_at: new Date('2023-04-15'),
  },
  {
    id: 4,
    first_name: 'Alice',
    last_name: 'Johnson',
    email: 'alice.johnson@example.com',
    gender: 'Female',
    ip_address: '192.168.1.4',
    days: 60,
    created_at: new Date('2023-07-01'),
  },
  {
    id: 5,
    first_name: 'Tom',
    last_name: 'Wilson',
    email: 'tom.wilson@example.com',
    gender: 'Male',
    ip_address: '192.168.1.5',
    days: 150,
    created_at: new Date('2023-03-01'),
  },
  {
    id: 6,
    first_name: 'Sarah',
    last_name: 'Lee',
    email: 'sarah.lee@example.com',
    gender: 'Female',
    ip_address: '192.168.1.6',
    days: 100,
    created_at: new Date('2023-08-01'),
  },
  {
    id: 7,
    first_name: 'Michael',
    last_name: 'Brown',
    email: 'michael.brown@example.com',
    gender: 'Male',
    ip_address: '192.168.1.7',
    days: 70,
    created_at: new Date('2023-09-15'),
  },
  {
    id: 8,
    first_name: 'Emily',
    last_name: 'Davis',
    email: 'emily.davis@example.com',
    gender: 'Female',
    ip_address: '192.168.1.8',
    days: 130,
    created_at: new Date('2023-02-01'),
  },
  {
    id: 9,
    first_name: 'David',
    last_name: 'Wilson',
    email: 'david.wilson@example.com',
    gender: 'Male',
    ip_address: '192.168.1.9',
    days: 80,
    created_at: new Date('2023-10-01'),
  },
  {
    id: 10,
    first_name: 'Jessica',
    last_name: 'Thompson',
    email: 'jessica.thompson@example.com',
    gender: 'Female',
    ip_address: '192.168.1.10',
    days: 110,
    created_at: new Date('2023-01-15'),
  },
  {
    id: 11,
    first_name: 'Christopher',
    last_name: 'Anderson',
    email: 'christopher.anderson@example.com',
    gender: 'Male',
    ip_address: '192.168.1.11',
    days: 90,
    created_at: new Date('2023-11-01'),
  },
];
